"""
tonnetz_tessellation.py
=======================

The {4, 6, 12} Archimedean tessellation -- dodecagons, hexagons and squares --
"generated by the first of the Archimedean tonnetze", after Figure 12 of

    J. R. Boland and L. P. Hughston,
    "Configurations, Tessellations and Tone Networks",
    arXiv:2505.08752.

This is a genuinely tonnetz-derived tessellation, in the sense of that paper:
it is the plane tiling that the first Archimedean tonnetz unfolds into. It is
one of the eleven Archimedean (semi-regular) tilings of the plane -- the
truncated trihexagonal tiling -- and is distinct from the Harmonious
voice-leading tessellation (see harmony_tiling.py), which is an orbifold slice
rather than a tonnetz.

Geometry
--------
All polygons share a common edge length s. At every vertex exactly three
polygons meet -- one square, one hexagon, one dodecagon -- and their interior
angles 90 + 120 + 150 = 360 close the vertex. Concretely:

    dodecagon circumradius  R12 = s / (2 sin(pi/12))  ~= 1.9319 s
    hexagon   circumradius  R6  = s
    square    circumradius  R4  = s / sqrt(2)

The dodecagon centres sit on a triangular lattice with constant
L = 2 * a12 + s, where a12 = R12 cos(pi/12) is the dodecagon apothem.
Hexagons sit at the triangle centroids of that lattice (two per cell);
squares sit at the lattice edge midpoints. This places every tile directly --
no search or flood fill -- so the build is cheap and bounded.

Musical reading (after the paper, Section V)
--------------------------------------------
Vertices carry triads; each edge carries the tone shared by the triads at its
two ends; the three edges at a vertex give the three tones of that triad.
Hamiltonian cycles ascend in fifths around a dodecagon's rim. For legibility
this module labels each dodecagon with the twelve triads in fifths order, so
the circle-of-fifths Hamiltonian can be read straight off the rim.

Usage
-----
    python3 tonnetz_tessellation.py                 # default SVG + PDF
    python3 tonnetz_tessellation.py --rings 3       # smaller / larger patch
    python3 tonnetz_tessellation.py --out mytiling

Produces a print-ready SVG and a paged PDF, white background with light
translucent fills (an ink-sparing substrate for tracing chord progressions).
"""

from __future__ import annotations
import argparse
import math

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import Polygon as MplPolygon
from matplotlib.backends.backend_pdf import PdfPages


# --------------------------------------------------------------------------
# Geometry
# --------------------------------------------------------------------------

S = 60.0                                  # common edge length (display units)
R12 = S / (2.0 * math.sin(math.pi / 12))  # dodecagon circumradius
A12 = R12 * math.cos(math.pi / 12)        # dodecagon apothem
R6 = S                                    # hexagon circumradius
R4 = S / math.sqrt(2.0)                   # square circumradius
L = 2.0 * A12 + S                          # dodecagon lattice constant

# triangular lattice vectors for the dodecagon centres
E1 = (L, 0.0)
E2 = (L * 0.5, L * math.sqrt(3.0) / 2.0)

# the twelve triads in fifths order, for the dodecagon rim Hamiltonian
FIFTHS = ["C", "G", "D", "A", "E", "B",
          "F\u266f", "D\u266d", "A\u266d", "E\u266d", "B\u266d", "F"]

# print appearance
BG = "#ffffff"
EDGE = "#3a342a"
INK = "#1a150d"
FILL_ALPHA = 0.20
COLORS = {
    "dod": "#cd7430",     # dodecagon  -- warm orange
    "hex": "#6b8db1",     # hexagon    -- blue
    "sq":  "#dcb648",     # square     -- yellow
}

PAPER = {                                  # (width, height) inches, portrait
    "letter":  (8.5, 11.0),
    "legal":   (8.5, 14.0),
    "a4":      (8.27, 11.69),
    "a3":      (11.69, 16.54),
    "tabloid": (11.0, 17.0),
}


def _ngon(cx, cy, n, R, phase_deg):
    """Regular n-gon vertices, counter-clockwise, first vertex at phase_deg."""
    return [(cx + R * math.cos(math.radians(phase_deg + 360.0 * k / n)),
             cy + R * math.sin(math.radians(phase_deg + 360.0 * k / n)))
            for k in range(n)]


def _centroid(pts):
    n = len(pts)
    return (round(sum(p[0] for p in pts) / n, 3),
            round(sum(p[1] for p in pts) / n, 3))


def build_tiling(rings: int = 4):
    """Build the {4,6,12} tessellation.

    `rings` sets how many dodecagon-lattice cells out from the origin are
    generated. Returns a list of tiles, each a dict:
        {type: 'dod'|'hex'|'sq', pts: [[x,y],...], cx, cy, label}
    Only dodecagons carry a musical `label` (a triad); hexagons and squares
    are connective cells and carry an empty label.
    """
    span = (rings + 1) * L
    tiles = []
    seen = set()

    def add(typ, poly, label=""):
        c = _centroid(poly)
        if (typ, c) in seen:
            return
        seen.add((typ, c))
        tiles.append(dict(type=typ, pts=[list(p) for p in poly],
                          cx=c[0], cy=c[1], label=label))

    rng = range(-rings - 1, rings + 2)

    # dodecagons on the triangular lattice; edges face 0,30,...,330 degrees
    for a in rng:
        for b in rng:
            cx = a * E1[0] + b * E2[0]
            cy = a * E1[1] + b * E2[1]
            if abs(cx) < span and abs(cy) < span:
                # label by fifths; the lattice coordinate fixes the triad
                idx = (7 * a + 2 * b) % 12          # ascends a fifth per step
                add("dod", _ngon(cx, cy, 12, R12, 15.0), FIFTHS[idx])

    # hexagons at the two triangle centroids of every lattice cell
    for a in rng:
        for b in rng:
            bx = a * E1[0] + b * E2[0]
            by = a * E1[1] + b * E2[1]
            for off in (((E1[0] + E2[0]) / 3.0, (E1[1] + E2[1]) / 3.0),
                        (2.0 * (E1[0] + E2[0]) / 3.0,
                         2.0 * (E1[1] + E2[1]) / 3.0)):
                hx, hy = bx + off[0], by + off[1]
                if abs(hx) < span and abs(hy) < span:
                    add("hex", _ngon(hx, hy, 6, R6, 0.0))

    # squares at every dodecagon-lattice edge midpoint
    edge_vecs = (E1, E2, (E2[0] - E1[0], E2[1] - E1[1]))
    for a in rng:
        for b in rng:
            bx = a * E1[0] + b * E2[0]
            by = a * E1[1] + b * E2[1]
            for ev in edge_vecs:
                mx, my = bx + ev[0] / 2.0, by + ev[1] / 2.0
                if abs(mx) < span and abs(my) < span:
                    ang = math.degrees(math.atan2(ev[1], ev[0]))
                    add("sq", _ngon(mx, my, 4, R4, ang + 45.0))

    return tiles


def crop(tiles, half_w, half_h):
    """Keep tiles whose centroid lies within a centred rectangle."""
    return [t for t in tiles
            if -half_w < t["cx"] < half_w and -half_h < t["cy"] < half_h]


def normalize(tiles, pad=30):
    """Shift + flip into SVG (y-down) coordinates. Returns (W, H, tiles)."""
    xs = [p[0] for t in tiles for p in t["pts"]]
    ys = [p[1] for t in tiles for p in t["pts"]]
    minx, maxx = min(xs), max(xs)
    miny, maxy = min(ys), max(ys)
    W, H = maxx - minx + 2 * pad, maxy - miny + 2 * pad
    out = []
    for t in tiles:
        nt = dict(t)
        nt["pts"] = [[round(x - minx + pad, 3), round(maxy - y + pad, 3)]
                     for x, y in t["pts"]]
        c = _centroid(nt["pts"])
        nt["cx"], nt["cy"] = c
        out.append(nt)
    return round(W, 1), round(H, 1), out


def verify(tiles):
    """Check the tiling. Returns a dict of interior adjacency counts.

    For a correct {4,6,12} tiling every interior dodecagon borders 6 hexagons
    and 6 squares; every interior hexagon borders 3 dodecagons and 3 squares;
    every interior square borders 2 dodecagons and 2 hexagons.
    """
    def edges(t):
        p = t["pts"]
        out = []
        for k in range(len(p)):
            a = (round(p[k][0], 2), round(p[k][1], 2))
            b = (round(p[(k + 1) % len(p)][0], 2),
                 round(p[(k + 1) % len(p)][1], 2))
            out.append(tuple(sorted([a, b])))
        return out

    emap = {}
    for i, t in enumerate(tiles):
        for e in edges(t):
            emap.setdefault(e, []).append(i)

    over = sum(1 for v in emap.values() if len(v) > 2)

    xs = [p[0] for t in tiles for p in t["pts"]]
    ys = [p[1] for t in tiles for p in t["pts"]]
    cx0, cy0 = (min(xs) + max(xs)) / 2, (min(ys) + max(ys)) / 2
    half = min(max(xs) - min(xs), max(ys) - min(ys)) * 0.22

    want = {"dod": (6, "hex", 6, "sq"),
            "hex": (3, "dod", 3, "sq"),
            "sq":  (2, "dod", 2, "hex")}
    good = bad = 0
    for i, t in enumerate(tiles):
        if abs(t["cx"] - cx0) > half or abs(t["cy"] - cy0) > half:
            continue
        nb = {"dod": 0, "hex": 0, "sq": 0}
        for e in edges(t):
            for j in emap[e]:
                if j != i:
                    nb[tiles[j]["type"]] += 1
        n1, t1, n2, t2 = want[t["type"]]
        if nb[t1] == n1 and nb[t2] == n2:
            good += 1
        else:
            bad += 1
    return {"edges_shared_by_more_than_2": over,
            "interior_tiles_correct": good,
            "interior_tiles_wrong": bad}


# --------------------------------------------------------------------------
# Rendering
# --------------------------------------------------------------------------

def _draw(ax, tiles, clip=None):
    """Draw all tiles; label dodecagons with their triad."""
    for t in tiles:
        ax.add_patch(MplPolygon(
            t["pts"], closed=True, facecolor=COLORS[t["type"]],
            alpha=FILL_ALPHA, edgecolor=EDGE, linewidth=1.1,
            joinstyle="round"))
    for t in tiles:
        ax.add_patch(MplPolygon(
            t["pts"], closed=True, fill=False,
            edgecolor=EDGE, linewidth=1.1, joinstyle="round"))

    def in_window(t):
        if clip is None:
            return True
        xl, xh, yl, yh = clip
        return xl <= t["cx"] <= xh and yl <= t["cy"] <= yh

    for t in tiles:
        if t["type"] != "dod" or not t["label"] or not in_window(t):
            continue
        ax.text(t["cx"], t["cy"], t["label"] + "M",
                ha="center", va="center", fontsize=0.30 * S,
                fontweight="bold", color=INK, family="monospace")


def render_svg(tiles, path):
    xs = [p[0] for t in tiles for p in t["pts"]]
    ys = [p[1] for t in tiles for p in t["pts"]]
    w, h = max(xs) - min(xs), max(ys) - min(ys)
    fig, ax = plt.subplots(figsize=(15.0, 15.0 * h / w))
    fig.patch.set_facecolor(BG)
    ax.set_facecolor(BG)
    _draw(ax, tiles)
    ax.set_xlim(min(xs), max(xs))
    ax.set_ylim(max(ys), min(ys))
    ax.set_aspect("equal")
    ax.axis("off")
    fig.subplots_adjust(left=0, right=1, top=1, bottom=0)
    fig.savefig(path, format="svg", facecolor=BG)
    plt.close(fig)
    print(f"  wrote {path}")


def render_pdf(tiles, path, paper, cols, page_rows, margin_in=0.4):
    xs = [p[0] for t in tiles for p in t["pts"]]
    ys = [p[1] for t in tiles for p in t["pts"]]
    minx, maxx = min(xs), max(xs)
    miny, maxy = min(ys), max(ys)
    total_w, total_h = maxx - minx, maxy - miny

    paper_w, paper_h = PAPER[paper]
    if total_w / total_h > 1.0:
        paper_w, paper_h = paper_h, paper_w
    sheet_w = paper_w - 2 * margin_in
    sheet_h = paper_h - 2 * margin_in

    span_x = total_w / cols
    span_y = total_h / page_rows
    sheet_aspect = sheet_w / sheet_h
    if span_x / span_y < sheet_aspect:
        span_x = span_y * sheet_aspect
    else:
        span_y = span_x / sheet_aspect

    print(f"  PDF: {cols * page_rows} sheet(s)  ({cols} x {page_rows}), "
          f"{paper} {'landscape' if paper_w > paper_h else 'portrait'}")

    with PdfPages(path) as pdf:
        for pr in range(page_rows):
            for pc in range(cols):
                fig = plt.figure(figsize=(paper_w, paper_h))
                fig.patch.set_facecolor(BG)
                ax = fig.add_axes([margin_in / paper_w, margin_in / paper_h,
                                   sheet_w / paper_w, sheet_h / paper_h])
                ax.set_facecolor(BG)

                x0 = minx + pc * (total_w / cols)
                y0 = miny + pr * (total_h / page_rows)
                _draw(ax, tiles, clip=(x0, x0 + span_x, y0, y0 + span_y))

                ax.set_xlim(x0, x0 + span_x)
                ax.set_ylim(y0 + span_y, y0)
                ax.set_aspect("equal")
                ax.axis("off")

                for fx in (0.0, 1.0):
                    for fy in (0.0, 1.0):
                        ax.plot([fx], [fy], marker="+", markersize=9,
                                markeredgewidth=0.8, color="#8a8275",
                                transform=ax.transAxes, clip_on=False)
                fig.text(0.5, margin_in / paper_h * 0.45,
                         f"{{4,6,12}} Archimedean tonnetz tessellation"
                         f"   .   row {pr + 1} of {page_rows}"
                         f"   .   col {pc + 1} of {cols}",
                         ha="center", va="center", fontsize=7,
                         color="#8a8275", family="monospace")
                pdf.savefig(fig, facecolor=BG)
                plt.close(fig)
    print(f"  wrote {path}")


# --------------------------------------------------------------------------
# CLI
# --------------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser(
        description="Generate the {4,6,12} Archimedean tonnetz tessellation.")
    ap.add_argument("--rings", type=int, default=4,
                    help="dodecagon-lattice radius (default 4)")
    ap.add_argument("--paper", default="letter", choices=sorted(PAPER),
                    help="PDF paper size (default letter)")
    ap.add_argument("--cols", type=int, default=3,
                    help="PDF sheet columns (default 3)")
    ap.add_argument("--page-rows", type=int, default=2,
                    help="PDF sheet rows (default 2)")
    ap.add_argument("--out", default="tonnetz_tessellation",
                    help="output basename")
    args = ap.parse_args()

    print("Building {4,6,12} Archimedean tonnetz tessellation ...")
    tiles = build_tiling(rings=args.rings)
    # trim the ragged lattice edge to a clean rectangle
    xs = [t["cx"] for t in tiles]
    ys = [t["cy"] for t in tiles]
    half_w = (max(xs) - min(xs)) * 0.34
    half_h = (max(ys) - min(ys)) * 0.34
    tiles = crop(tiles, half_w, half_h)
    W, H, tiles = normalize(tiles)

    n = {"dod": 0, "hex": 0, "sq": 0}
    for t in tiles:
        n[t["type"]] += 1
    print(f"  {len(tiles)} tiles  ({n['dod']} dodecagons, {n['hex']} hexagons, "
          f"{n['sq']} squares)")

    v = verify(tiles)
    if v["edges_shared_by_more_than_2"] == 0 and v["interior_tiles_wrong"] == 0:
        print(f"  geometry check passed: no overlaps, all "
              f"{v['interior_tiles_correct']} interior tiles have the "
              f"correct {{4,6,12}} adjacency")
    else:
        print(f"  geometry check WARNING: {v}")

    render_svg(tiles, f"{args.out}.svg")
    render_pdf(tiles, f"{args.out}.pdf", args.paper, args.cols, args.page_rows)
    print("Done.")


if __name__ == "__main__":
    main()
